# Generated by Django 3.1 on 2020-08-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('author_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=100)),
                ('recipe_description', models.TextField()),
                ('recipe_time_required', models.CharField(max_length=15)),
                ('recipe_instruction', models.TextField()),
                ('recipe_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_box_v1.authormodel')),
            ],
        ),
    ]
